// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_sdui_challenge/test/features/car_management/data/repository/car_management_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_sdui_challenge/features/car_management/data/models/car_attribute_model.dart'
    as _i6;
import 'package:flutter_sdui_challenge/features/car_management/data/models/get_cars_response_model.dart'
    as _i7;
import 'package:flutter_sdui_challenge/features/car_management/data/source/local/car_management_local_data_source.dart'
    as _i5;
import 'package:flutter_sdui_challenge/features/car_management/data/source/remote/car_management_remote_data_source.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ICarManagementRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockICarManagementRemoteDataSource extends _i1.Mock
    implements _i3.ICarManagementRemoteDataSource {
  MockICarManagementRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Response<dynamic>> getFormFields() => (super.noSuchMethod(
        Invocation.method(
          #getFormFields,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Response<dynamic>>.value(_FakeResponse_0<dynamic>(
          this,
          Invocation.method(
            #getFormFields,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Response<dynamic>>);
}

/// A class which mocks [ICarManagementLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockICarManagementLocalDataSource extends _i1.Mock
    implements _i5.ICarManagementLocalDataSource {
  MockICarManagementLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> addNewCar(List<_i6.CarAttributeModel>? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #addNewCar,
          [request],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCar(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCar,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i7.GetCarsResponseModel>> getAllCars() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllCars,
          [],
        ),
        returnValue: _i4.Future<List<_i7.GetCarsResponseModel>>.value(
            <_i7.GetCarsResponseModel>[]),
      ) as _i4.Future<List<_i7.GetCarsResponseModel>>);
}
